### ISSUE TITLE
Improve the look of the input forms

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/jupyter-template#2]
Right now there are no margins and no title

**Comment by u8sand** [comment]
Which profile are you referring to? I want to impart as few explicit visual requirements as possible as to enable complete customization of the UI

**Comment by u8sand** [comment]
The example looks like this:

![image](https://user-images.githubusercontent.com/1341861/78905916-aa362600-7a4c-11ea-81b9-4536e592fdf2.png)

It has both a title & margins

**Comment by AviMaayan** [comment]
![form](https://user-images.githubusercontent.com/12749033/78906326-36484d80-7a4d-11ea-9563-505e028d674e.png)

I was reviewing Minji's RNA-seq pipeline from here http://10.90.122.191/ (only accessible via VPN). I guess she should be able to beautify it.

**Comment by AviMaayan** [comment]
The example that you are showing looks nice!

**Comment by u8sand** [comment]
She can use that by simply providing `--profile=biojupies` as an argument when she runs it.
