### ISSUE TITLE
Evaluation persistence

### ISSUE THREAD

**Issue by u8sand** [MaayanLab/jupyter-template#9]
People should be able to go back to an already evaluated notebook and see the results.

Also if you get disconnected during evaluation, your client should continue where it left off instead of restarting everything.

For this effort, the session ID should be available in the URL

**Comment by u8sand** [comment]
I'm thinking we can construct a session ID which is simply a hash of all relevant information that goes into creating the notebook:
- form input
- checksums of any uploaded files
- checksum of notebook itself

Unique session IDs become directories where the notebook is evaluated, this ID is on the URL -- this evaluation should happen **once**, and the resulting notebook saved in that directory along with input files. Re-visiting the site will show the already evaluated notebook, refreshing in the middle should show where current evaluation is.

**Comment by AviMaayan** [comment]
This sounds great...
